# Generated by Django 6.0.6 on 2026-09-28 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer_portal', '0017_vehicledispatchsale_payment_mode'),
        ('dealers', '0010_dealerreturn_dealerreturnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('VEHICLE_FUEL', 'Vehicle Fuel'), ('VEHICLE_REPAIR', 'Vehicle Repair'), ('VEHICLE_MAINTENANCE', 'Vehicle Maintenance'), ('OFFICE', 'Office Expense'), ('SALARY', 'Salary / Allowance'), ('TRANSPORT', 'Transport'), ('LOADING', 'Loading / Unloading'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer_portal.dealervehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DealerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('SHOP', 'Shop Expense'), ('STAFF', 'Staff Expense'), ('VEHICLE_FUEL', 'Vehicle Fuel'), ('VEHICLE_REPAIR', 'Vehicle Repair'), ('VEHICLE_MAINTENANCE', 'Vehicle Maintenance'), ('ELECTRICITY', 'Electricity'), ('RENT', 'Rent'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dealers.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('FOOD', 'Food / Snacks'), ('PARKING', 'Parking'), ('DRIVER', 'Driver Expense'), ('LOADING', 'Loading / Unloading'), ('REPAIR', 'Emergency Repair'), ('TOLL', 'Toll / Road Expense'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dealer_portal.vehicletrip')),
            ],
        ),
    ]
