# Generated by Django 6.0.6 on 2026-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_created_at_product_minimum_stock_product_sku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionitem',
            old_name='quantity',
            new_name='quantity_produced',
        ),
        migrations.RemoveField(
            model_name='production',
            name='product',
        ),
        migrations.RemoveField(
            model_name='production',
            name='quantity',
        ),
        migrations.AddField(
            model_name='production',
            name='batch_number',
            field=models.CharField(default='BATCH000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionitem',
            name='quantity_wasted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
