# Generated by Django 6.0.6 on 2026-06-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_quantity_productionitem_quantity_produced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
