# Generated by Django 6.0.6 on 2026-06-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
