# Generated by Django 6.0.6 on 2026-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
