# Generated by Django 6.0.6 on 2026-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_dispatchitem_amount_dispatchitem_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
