# Generated by Django 6.0.6 on 2026-06-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_dealerstock_delete_dealeradmin'),
        ('inventory', '0008_remove_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='dealerstock',
            unique_together={('dealer', 'product')},
        ),
    ]
