# Generated by Django 6.0.6 on 2026-06-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_dealerstock_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealerStock',
        ),
    ]
