# Generated by Django 6.0.6 on 2026-06-17 04:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0008_dealerledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerpayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('ONLINE', 'Online')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealerpayment',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
