# Generated by Django 6.0.5 on 2026-06-23 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealercustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dealercustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
