# Generated by Django 6.0.5 on 2026-06-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0002_dealercustomer_created_at_dealercustomer_email_and_more'),
        ('dealers', '0010_dealerreturn_dealerreturnitem'),
        ('inventory', '0016_dispatch_approved_at_dispatch_dealer_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerSalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=100, unique=True)),
                ('return_date', models.DateField()),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_portal.dealersale')),
            ],
        ),
        migrations.CreateModel(
            name='DealerSalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_portal.dealersaleitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dealer_portal.dealersalesreturn')),
            ],
        ),
    ]
