# Generated by Django 6.0.5 on 2026-06-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0003_dealersalesreturn_dealersalesreturnitem'),
        ('dealers', '0010_dealerreturn_dealerreturnitem'),
        ('inventory', '0016_dispatch_approved_at_dispatch_dealer_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_no', models.CharField(max_length=100, unique=True)),
                ('dispatch_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_portal.dealervehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sold_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('breakage_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leakage_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sponsor_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dealer_portal.vehicledispatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
