# Generated by Django 6.0.6 on 2026-06-30 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0004_dealervehicle_vehicledispatch_vehicledispatchitem'),
        ('dealers', '0010_dealerreturn_dealerreturnitem'),
        ('inventory', '0016_dispatch_approved_at_dispatch_dealer_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DEALER', 'Dealer'), ('VEHICLE', 'Vehicle')], default='DEALER', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('sponsor_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer_portal.dealercustomer')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('vehicle_dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer_portal.vehicledispatch')),
            ],
        ),
    ]
