# Generated by Django 6.0.6 on 2026-06-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0005_dealersponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealersponsor',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer_portal.dealervehicle'),
        ),
        migrations.AlterField(
            model_name='dealersponsor',
            name='source',
            field=models.CharField(choices=[('DEALER', 'Dealer'), ('VEHICLE', 'Vehicle')], max_length=20),
        ),
    ]
