# Generated by Django 6.0.6 on 2026-07-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0006_dealersponsor_vehicle_alter_dealersponsor_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealersale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dealer_portal.dealercustomer'),
        ),
    ]
