# Generated by Django 6.0.6 on 2026-07-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0007_alter_dealersale_customer'),
        ('inventory', '0016_dispatch_approved_at_dispatch_dealer_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.PositiveIntegerField()),
                ('dispatch_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='dealer_portal.vehicledispatch')),
            ],
            options={
                'ordering': ['trip_no'],
                'unique_together': {('dispatch', 'trip_no')},
            },
        ),
        migrations.CreateModel(
            name='VehicleTripItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sold_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('breakage_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leakage_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sponsor_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dealer_portal.vehicletrip')),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleDispatchItem',
        ),
    ]
