# Generated by Django 6.0.6 on 2026-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0008_vehicletrip_vehicletripitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletrip',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
