# Generated by Django 6.0.6 on 2026-08-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0010_vehicledispatchsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledispatch',
            name='dispatch_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledispatch',
            name='driver_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
