# Generated by Django 6.0.6 on 2026-08-17 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0011_vehicledispatch_dispatch_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealersaleitem',
            name='bonus_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vehicledispatchsale',
            name='bonus_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
       migrations.AddField(
            model_name='vehicledispatchsale',
            name='customer',
            field=models.ForeignKey(
                to='dealer_portal.dealercustomer',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vehicle_sales',
                null=True,
                blank=True,
            ),
        ),

    ]
