# Generated by Django 6.0.6 on 2026-08-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0012_dealersaleitem_bonus_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledispatchsale',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_sales', to='dealer_portal.dealercustomer'),
            preserve_default=False,
        ),
    ]
