# Generated by Django 6.0.6 on 2026-08-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0013_alter_vehicledispatchsale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletripitem',
            name='bonus_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
