# Generated by Django 6.0.6 on 2026-08-17 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0014_vehicletripitem_bonus_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercustomerledger',
            name='bonus_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dealercustomerledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealercustomerledger',
            name='entry_type',
            field=models.CharField(max_length=30),
        ),
    ]
