# Generated by Django 6.0.6 on 2026-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0015_dealercustomerledger_bonus_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealercustomerledger',
            name='bonus_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
