# Generated by Django 6.0.6 on 2026-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_portal', '0016_alter_dealercustomerledger_bonus_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledispatchsale',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('FONEPAY', 'Fonepay'), ('CREDIT', 'Credit')], default='CASH', max_length=20),
        ),
    ]
