# Generated by Django 6.0.6 on 2026-06-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerledger',
            name='remarks',
        ),
    ]
