# Generated by Django 6.0.5 on 2026-06-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='entry_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PAYMENT', 'Payment'), ('SALES_RETURN', 'Sales Return')], max_length=20),
        ),
    ]
