# Generated by Django 6.0.6 on 2026-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='returned_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
