# Generated by Django 6.0.6 on 2026-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleitem_returned_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='bonus_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
