# Generated by Django 6.0.6 on 2026-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_saleitem_bonus_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='bonus_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerledger',
            name='entry_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PAYMENT', 'Payment')], max_length=20),
        ),
    ]
