# Generated by Django 6.0.6 on 2026-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_customerledger_bonus_quantity_customerledger_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='bonus_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
